// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGlacRBFK8tVEf9iv9s4wJUBpPMd7weK4',
    appId: '1:379066047440:web:d758b1be84e26d4b6737d5',
    messagingSenderId: '379066047440',
    projectId: 'invoiceapp-9187f',
    authDomain: 'invoiceapp-9187f.firebaseapp.com',
    storageBucket: 'invoiceapp-9187f.firebasestorage.app',
    measurementId: 'G-J89NW1Z72Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVSXx2OKvLrBudRORqDYvsir63TpO4DT8',
    appId: '1:379066047440:android:dfe0b5cb9a28cd446737d5',
    messagingSenderId: '379066047440',
    projectId: 'invoiceapp-9187f',
    storageBucket: 'invoiceapp-9187f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpO7hNeMyuuvFnj6ykrA-aJJp6nM1KZo8',
    appId: '1:379066047440:ios:f7fcc99e92f0974f6737d5',
    messagingSenderId: '379066047440',
    projectId: 'invoiceapp-9187f',
    storageBucket: 'invoiceapp-9187f.firebasestorage.app',
    iosBundleId: 'com.example.annaInvoiceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpO7hNeMyuuvFnj6ykrA-aJJp6nM1KZo8',
    appId: '1:379066047440:ios:f7fcc99e92f0974f6737d5',
    messagingSenderId: '379066047440',
    projectId: 'invoiceapp-9187f',
    storageBucket: 'invoiceapp-9187f.firebasestorage.app',
    iosBundleId: 'com.example.annaInvoiceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGlacRBFK8tVEf9iv9s4wJUBpPMd7weK4',
    appId: '1:379066047440:web:18d36bb6d89910486737d5',
    messagingSenderId: '379066047440',
    projectId: 'invoiceapp-9187f',
    authDomain: 'invoiceapp-9187f.firebaseapp.com',
    storageBucket: 'invoiceapp-9187f.firebasestorage.app',
    measurementId: 'G-0SHZ6WTD1S',
  );
}
